package com.android.inputdevices;
/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class raw {
        public static final int keyboard_layout_arabic = 0x7f010000;
        public static final int keyboard_layout_azerbaijani = 0x7f010001;
        public static final int keyboard_layout_belgian = 0x7f010002;
        public static final int keyboard_layout_brazilian = 0x7f010003;
        public static final int keyboard_layout_bulgarian = 0x7f010004;
        public static final int keyboard_layout_croatian_and_slovenian = 0x7f010005;
        public static final int keyboard_layout_czech = 0x7f010006;
        public static final int keyboard_layout_danish = 0x7f010007;
        public static final int keyboard_layout_english_uk = 0x7f010008;
        public static final int keyboard_layout_english_us = 0x7f010009;
        public static final int keyboard_layout_english_us_colemak = 0x7f01000a;
        public static final int keyboard_layout_english_us_dvorak = 0x7f01000b;
        public static final int keyboard_layout_english_us_intl = 0x7f01000c;
        public static final int keyboard_layout_english_us_workman = 0x7f01000d;
        public static final int keyboard_layout_estonian = 0x7f01000e;
        public static final int keyboard_layout_finnish = 0x7f01000f;
        public static final int keyboard_layout_french = 0x7f010010;
        public static final int keyboard_layout_french_ca = 0x7f010011;
        public static final int keyboard_layout_german = 0x7f010012;
        public static final int keyboard_layout_greek = 0x7f010013;
        public static final int keyboard_layout_hebrew = 0x7f010014;
        public static final int keyboard_layout_hungarian = 0x7f010015;
        public static final int keyboard_layout_icelandic = 0x7f010016;
        public static final int keyboard_layout_italian = 0x7f010017;
        public static final int keyboard_layout_latvian_qwerty = 0x7f010018;
        public static final int keyboard_layout_lithuanian = 0x7f010019;
        public static final int keyboard_layout_norwegian = 0x7f01001a;
        public static final int keyboard_layout_persian = 0x7f01001b;
        public static final int keyboard_layout_polish = 0x7f01001c;
        public static final int keyboard_layout_portuguese = 0x7f01001d;
        public static final int keyboard_layout_russian = 0x7f01001e;
        public static final int keyboard_layout_russian_mac = 0x7f01001f;
        public static final int keyboard_layout_slovak = 0x7f010020;
        public static final int keyboard_layout_spanish = 0x7f010021;
        public static final int keyboard_layout_spanish_latin = 0x7f010022;
        public static final int keyboard_layout_swedish = 0x7f010023;
        public static final int keyboard_layout_swiss_french = 0x7f010024;
        public static final int keyboard_layout_swiss_german = 0x7f010025;
        public static final int keyboard_layout_turkish = 0x7f010026;
        public static final int keyboard_layout_ukrainian = 0x7f010027;
    }

    public static final class string {
        public static final int app_label = 0x7f020000;
        public static final int keyboard_layout_arabic = 0x7f020001;
        public static final int keyboard_layout_azerbaijani = 0x7f020002;
        public static final int keyboard_layout_belgian = 0x7f020003;
        public static final int keyboard_layout_brazilian = 0x7f020004;
        public static final int keyboard_layout_bulgarian = 0x7f020005;
        public static final int keyboard_layout_croatian = 0x7f020006;
        public static final int keyboard_layout_czech = 0x7f020007;
        public static final int keyboard_layout_danish = 0x7f020008;
        public static final int keyboard_layout_english_uk_label = 0x7f020009;
        public static final int keyboard_layout_english_us_colemak_label = 0x7f02000a;
        public static final int keyboard_layout_english_us_dvorak_label = 0x7f02000b;
        public static final int keyboard_layout_english_us_intl = 0x7f02000c;
        public static final int keyboard_layout_english_us_label = 0x7f02000d;
        public static final int keyboard_layout_english_us_workman_label = 0x7f02000e;
        public static final int keyboard_layout_estonian = 0x7f02000f;
        public static final int keyboard_layout_finnish = 0x7f020010;
        public static final int keyboard_layout_french_ca_label = 0x7f020011;
        public static final int keyboard_layout_french_label = 0x7f020012;
        public static final int keyboard_layout_german_label = 0x7f020013;
        public static final int keyboard_layout_greek = 0x7f020014;
        public static final int keyboard_layout_hebrew = 0x7f020015;
        public static final int keyboard_layout_hungarian = 0x7f020016;
        public static final int keyboard_layout_icelandic = 0x7f020017;
        public static final int keyboard_layout_italian = 0x7f020018;
        public static final int keyboard_layout_latvian = 0x7f020019;
        public static final int keyboard_layout_lithuanian = 0x7f02001a;
        public static final int keyboard_layout_norwegian = 0x7f02001b;
        public static final int keyboard_layout_persian = 0x7f02001c;
        public static final int keyboard_layout_polish = 0x7f02001d;
        public static final int keyboard_layout_portuguese = 0x7f02001e;
        public static final int keyboard_layout_russian_label = 0x7f02001f;
        public static final int keyboard_layout_russian_mac_label = 0x7f020020;
        public static final int keyboard_layout_slovak = 0x7f020021;
        public static final int keyboard_layout_slovenian = 0x7f020022;
        public static final int keyboard_layout_spanish_label = 0x7f020023;
        public static final int keyboard_layout_spanish_latin = 0x7f020024;
        public static final int keyboard_layout_swedish = 0x7f020025;
        public static final int keyboard_layout_swiss_french_label = 0x7f020026;
        public static final int keyboard_layout_swiss_german_label = 0x7f020027;
        public static final int keyboard_layout_turkish = 0x7f020028;
        public static final int keyboard_layout_ukrainian = 0x7f020029;
        public static final int keyboard_layouts_label = 0x7f02002a;
    }

    public static final class xml {
        public static final int keyboard_layouts = 0x7f030000;
    }
}
